/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Sibre.Telas;

import br.com.Sibre.DAL.ModuloConexao;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import tabela.Conexao;

/**
 *
 * @author Jorge Alves Peixoto
 */
public class Gravar_imagem extends javax.swing.JFrame {

    ModuloConexao con = new ModuloConexao();

    private void Gravi() {
        con.conector();
        String caminho = jl.getIcon().toString();
        InputStream fis;
        File file = new File(caminho);
        //file.getName();
        String sql = "INSERT INTO img (id_img, foto_img) VALUES (?,?)";
        try {
            fis = new FileInputStream(file);         
            PreparedStatement ps = con.conn.prepareStatement(sql);
            ps.setString(1, TxtId.getText());
            ps.setBinaryStream(2, fis, (int) file.length());
           
            if(jl == null){
                 JOptionPane.showMessageDialog(null, "Preenchimento obrgatório");
            } else {
           int adicionado = ps.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Imagem inserida com sucesso");

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void BuscaNoBanco() {
        con.conector();
        con.executaSQL("SELECT foto_img FROM img where id_img = 5");
        try {
            con.rs.beforeFirst();
            while (con.rs.next()) {
             //  int id_img = con.rs.getInt("foto_img"); 
                byte[] imgBytes = ((byte[]) con.rs.getBytes("foto_img"));
                ImageIcon pic = null;
                pic = new ImageIcon(imgBytes);
                Image scaled = pic.getImage().getScaledInstance(jl.getWidth(), jl.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(scaled);
                jl.setIcon(icon);//Adapta o tamanho da img para ficar do tamanho da label
                //jl.setIcon(pic);
                FileOutputStream fos;
                String nome_foto = "teste";
                //nome_foto = JOptionPane.showInputDialog("Digite um nome para a foto ou imagem!");
//                fos = new FileOutputStream("Bibliotecas\\Imagens\\" + nome_foto + ".jpg");
                //fos = new FileOutputStream("C:/Tabela/img/teste.jpg");
//                fos.write((byte[]) con.rs.getBytes("foto_img"));
//                fos.write(con.rs.getBytes("foto_img"));
//                fos.close();
            }
        } catch (SQLException ex) {
            System.out.println("Erro " + ex);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(Gravar_imagem.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(Gravar_imagem.class.getName()).log(Level.SEVERE, null, ex);
//        }
        con.desconecata();
    }
    }
    /**
     * Creates new form Gravar_imagem
     */
    public Gravar_imagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnDirFoto = new javax.swing.JButton();
        BtnBucaFoto = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        BtnbuscadoBanco = new javax.swing.JButton();
        jl = new javax.swing.JLabel();
        LblId = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        txtcadnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnDirFoto.setText("foto no caminho fixo");
        BtnDirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDirFotoActionPerformed(evt);
            }
        });

        BtnBucaFoto.setText("selecionando caminho");
        BtnBucaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBucaFotoActionPerformed(evt);
            }
        });

        btGravar.setText("grava/altera");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        BtnbuscadoBanco.setText("buscar/ banco");
        BtnbuscadoBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbuscadoBancoActionPerformed(evt);
            }
        });

        jl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LblId.setText("Id");

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnDirFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBucaFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnbuscadoBanco)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtcadnome, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblId)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcadnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnDirFoto)
                        .addComponent(BtnBucaFoto)
                        .addComponent(btGravar))
                    .addComponent(BtnbuscadoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(547, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDirFotoActionPerformed
        ImageIcon pic = new ImageIcon("Bibliotecas\\Imagens\\Cosinheira.jpg");
        Image scaled = pic.getImage().getScaledInstance(jl.getWidth(), jl.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon icon = new ImageIcon(scaled);
        this.jl.setIcon(icon);

    }//GEN-LAST:event_BtnDirFotoActionPerformed

    private void BtnBucaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBucaFotoActionPerformed
        try {
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File("Documentos/imagens"));
            file.setDialogTitle("Carregar Imagem da Pessoa");
            file.showOpenDialog(this);
            String foto = ""+file.getSelectedFile().getName();
            txtcadnome.setText(foto);
           // jl.setIcon(new ImageIcon("Documentos/imagens/"+txtcadnome.getText()));
            jl.setIcon(new ImageIcon(file.getSelectedFile().getPath()));
            //jl.setText(file.getSelectedFile().getPath());
        } catch (Exception e) {
            jl.setIcon(new ImageIcon("Bibliotecas\\Imagens"+e));
        }
    }//GEN-LAST:event_BtnBucaFotoActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        Gravi();
    }//GEN-LAST:event_btGravarActionPerformed

    private void BtnbuscadoBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbuscadoBancoActionPerformed
        BuscaNoBanco();

    }//GEN-LAST:event_BtnbuscadoBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gravar_imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gravar_imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gravar_imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gravar_imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gravar_imagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBucaFoto;
    private javax.swing.JButton BtnDirFoto;
    private javax.swing.JButton BtnbuscadoBanco;
    private javax.swing.JLabel LblId;
    private javax.swing.JTextField TxtId;
    private javax.swing.JButton btGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl;
    private javax.swing.JTextField txtcadnome;
    // End of variables declaration//GEN-END:variables
}
