/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Sibre.Telas;

import br.com.Sibre.DAL.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.HashMap;
//import net.sf.jasperreports.engine.JRResultSetDataSource;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author T69779848134
 */
public class Menu extends javax.swing.JFrame {

    ModuloConexao conexao = new ModuloConexao();

    private static Menu instancia;
//Depois criei o seguinte método no formulário principal:

    public static Menu getInstance() { // MÉTODO QUE VERIFICA SE A INSTANCIA JÁ ESTÁ CRIADA (SINGLETON)
        if (instancia == null) {
            instancia = new Menu();
        }
        return instancia;
    }

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        conexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskTop = new javax.swing.JDesktopPane();
        LblSibre = new javax.swing.JLabel();
        BtnMenCad = new javax.swing.JButton();
        BtnMenuCant = new javax.swing.JButton();
        BtnMenuFamilia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        MenCad = new javax.swing.JMenuItem();
        MenFami = new javax.swing.JMenuItem();
        MenCantina = new javax.swing.JMenuItem();
        MenInv = new javax.swing.JMenuItem();
        MenuPedidosFeitos = new javax.swing.JMenuItem();
        MenuPedido_Oracao = new javax.swing.JMenuItem();
        MenRel = new javax.swing.JMenu();
        MenuRelMem = new javax.swing.JMenuItem();
        MenRelFamilia = new javax.swing.JMenuItem();
        MenRelCantina = new javax.swing.JMenuItem();
        MenuRelInventario = new javax.swing.JMenuItem();
        MenSobre = new javax.swing.JMenu();
        MenSobreOpc = new javax.swing.JMenuItem();
        MenAjuda = new javax.swing.JMenu();
        MenuOpSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(192, 212, 214));
        setMaximumSize(new java.awt.Dimension(1400, 732));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        DeskTop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeskTop.setMaximumSize(new java.awt.Dimension(1190, 680));
        DeskTop.setPreferredSize(new java.awt.Dimension(1130, 680));

        LblSibre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Sibre/Imagens/SibreHoje.jpeg"))); // NOI18N
        LblSibre.setText("jLabel4");

        DeskTop.setLayer(LblSibre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DeskTopLayout = new javax.swing.GroupLayout(DeskTop);
        DeskTop.setLayout(DeskTopLayout);
        DeskTopLayout.setHorizontalGroup(
            DeskTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeskTopLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(LblSibre, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        DeskTopLayout.setVerticalGroup(
            DeskTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeskTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblSibre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );

        BtnMenCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Sibre/Imagens/cadastro-clientes.png"))); // NOI18N
        BtnMenCad.setText("Cadastro de Membro e Congregados");
        BtnMenCad.setFocusable(false);
        BtnMenCad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMenCad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMenCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenCadActionPerformed(evt);
            }
        });

        BtnMenuCant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Sibre/Imagens/Pedido de oração.1.png"))); // NOI18N
        BtnMenuCant.setText("Formulario de Vendas da Cantina");
        BtnMenuCant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMenuCant.setFocusable(false);
        BtnMenuCant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMenuCant.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMenuCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuCantActionPerformed(evt);
            }
        });

        BtnMenuFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Sibre/Imagens/depositphotos_86670914-stock-illustration-family-church.jpg"))); // NOI18N
        BtnMenuFamilia.setText("Formulario de Cadastro Familias");
        BtnMenuFamilia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMenuFamilia.setFocusable(false);
        BtnMenuFamilia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMenuFamilia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnMenuFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuFamiliaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Sibre/Imagens/controle de inventario.png"))); // NOI18N
        jButton1.setToolTipText("Inventarios");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setPreferredSize(new java.awt.Dimension(139, 135));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setText("Deus seja Louvado");

        lblData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblData.setText("Data");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seja Bem vindo");

        jMenuBar1.setBackground(new java.awt.Color(210, 237, 227));
        jMenuBar1.setEnabled(false);

        Menu.setBackground(new java.awt.Color(206, 240, 230));
        Menu.setText("Cadastro");
        Menu.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        MenCad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenCad.setText("Membros");
        MenCad.setEnabled(false);
        MenCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadActionPerformed(evt);
            }
        });
        Menu.add(MenCad);

        MenFami.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenFami.setText("Familia");
        MenFami.setEnabled(false);
        MenFami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenFamiActionPerformed(evt);
            }
        });
        Menu.add(MenFami);

        MenCantina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenCantina.setText("Cantina");
        MenCantina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCantinaActionPerformed(evt);
            }
        });
        Menu.add(MenCantina);

        MenInv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenInv.setText("Inventario");
        MenInv.setEnabled(false);
        MenInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenInvActionPerformed(evt);
            }
        });
        Menu.add(MenInv);

        MenuPedidosFeitos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuPedidosFeitos.setText("Pedidos Feitos");
        MenuPedidosFeitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPedidosFeitosActionPerformed(evt);
            }
        });
        Menu.add(MenuPedidosFeitos);

        MenuPedido_Oracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuPedido_Oracao.setText("Pedidos de Oração");
        MenuPedido_Oracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPedido_OracaoActionPerformed(evt);
            }
        });
        Menu.add(MenuPedido_Oracao);

        jMenuBar1.add(Menu);

        MenRel.setBackground(new java.awt.Color(208, 234, 229));
        MenRel.setText("Relatorios");
        MenRel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        MenuRelMem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenuRelMem.setText("Membros");
        MenuRelMem.setEnabled(false);
        MenuRelMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelMemActionPerformed(evt);
            }
        });
        MenRel.add(MenuRelMem);

        MenRelFamilia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenRelFamilia.setText("Familias");
        MenRelFamilia.setEnabled(false);
        MenRelFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelFamiliaActionPerformed(evt);
            }
        });
        MenRel.add(MenRelFamilia);

        MenRelCantina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenRelCantina.setText("Cantina");
        MenRelCantina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelCantinaActionPerformed(evt);
            }
        });
        MenRel.add(MenRelCantina);

        MenuRelInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenuRelInventario.setText("Inventario");
        MenuRelInventario.setEnabled(false);
        MenuRelInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelInventarioActionPerformed(evt);
            }
        });
        MenRel.add(MenuRelInventario);

        jMenuBar1.add(MenRel);

        MenSobre.setBackground(new java.awt.Color(208, 240, 232));
        MenSobre.setText("Ajuda");
        MenSobre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        MenSobreOpc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenSobreOpc.setText("sobre");
        MenSobreOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSobreOpcActionPerformed(evt);
            }
        });
        MenSobre.add(MenSobreOpc);

        jMenuBar1.add(MenSobre);

        MenAjuda.setBackground(new java.awt.Color(208, 236, 231));
        MenAjuda.setText("Opções");
        MenAjuda.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N

        MenuOpSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MenuOpSair.setText("Sair");
        MenuOpSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpSairActionPerformed(evt);
            }
        });
        MenAjuda.add(MenuOpSair);

        jMenuBar1.add(MenAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMenuCant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(BtnMenuFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                    .addComponent(BtnMenCad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeskTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addGap(333, 333, 333)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblData)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnMenCad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtnMenuFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BtnMenuCant, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DeskTop, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1416, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadActionPerformed
        TelaCadastro cadastro = new TelaCadastro();
        cadastro.setVisible(true);
        DeskTop.add(cadastro);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_MenCadActionPerformed

    private void MenFamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenFamiActionPerformed
        TelaFamilia fam = new TelaFamilia();
        fam.setVisible(true);
        DeskTop.add(fam);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_MenFamiActionPerformed

    private void MenCantinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCantinaActionPerformed
        TelaCantina cosi = new TelaCantina();
        cosi.setVisible(true);
        DeskTop.add(cosi);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_MenCantinaActionPerformed

    private void MenInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenInvActionPerformed
        TelaInventario inv = new TelaInventario();
        inv.setVisible(true);
        DeskTop.add(inv);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_MenInvActionPerformed

    private void MenRelFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelFamiliaActionPerformed
//        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
//            conexao.conector();
//            try {
//                conexao.executaSQL("select * from familia;");
//                JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
//                JasperPrint print = JasperFillManager.fillReport("Reports/Cantina.jasper", new HashMap(), relatResult);
//                JasperViewer jv = new JasperViewer(print, false);
//                jv.setVisible(true);
//                jv.toFront();
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
//        }
    }//GEN-LAST:event_MenRelFamiliaActionPerformed

    private void MenRelCantinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelCantinaActionPerformed
        // Essa função é para gerar relatório
//        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
//            conexao.conector();
//            //imprimindo o relatório com o framework JasperReports
//            try {
//                conexao.executaSQL("select * from venda order by dataq desc;");
//                JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
//                JasperPrint print = JasperFillManager.fillReport("Reports/Cantina.jasper", new HashMap(), relatResult);
//                JasperViewer jv = new JasperViewer(print, false); //Cria instancia para impressão
//                jv.setVisible(true); //chama o relatório para visualização
//                jv.toFront(); // set o formuloari a frente da aplicação
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
//
//        }
    }//GEN-LAST:event_MenRelCantinaActionPerformed

    private void MenuRelInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelInventarioActionPerformed
//        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
//            conexao.conector();
//            //imprimindo o relatório com o framework JasperReports
//            try {
//                conexao.executaSQL("select * from inventario order by dataq desc;");
//                JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
//                JasperPrint print = JasperFillManager.fillReport("C:\\Users\\t69779848134\\Documents\\NetBeansProjects\\ProjetoSibre1.9\\src\\Relatórios\\Inventario.jasper", new HashMap(), relatResult);
//                JasperViewer jv = new JasperViewer(print, false); //Cria instancia para impressão
//                jv.setVisible(true); //chama o relatório para visualização
//                jv.toFront(); // set o formuloari a frente da aplicação
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
//
//        }
    }//GEN-LAST:event_MenuRelInventarioActionPerformed

    private void MenSobreOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSobreOpcActionPerformed
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_MenSobreOpcActionPerformed

    private void MenuOpSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?!", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuOpSairActionPerformed

    private void BtnMenCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenCadActionPerformed
        TelaCadastro cadastro = new TelaCadastro();
        cadastro.setVisible(true);
        DeskTop.add(cadastro);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_BtnMenCadActionPerformed

    private void BtnMenuCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuCantActionPerformed
        TelaPedidosFeitos feito = new TelaPedidosFeitos();
        feito.setVisible(true);
        DeskTop.add(feito);
        LblSibre.setVisible(false);
//        PedidosdeOraçoes oracoes = new PedidosdeOraçoes();
//        oracoes.setVisible(true);

    }//GEN-LAST:event_BtnMenuCantActionPerformed

    private void BtnMenuFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuFamiliaActionPerformed
        TelaFamilia fam = new TelaFamilia();
        fam.setVisible(true);
        DeskTop.add(fam);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_BtnMenuFamiliaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaInventario inv = new TelaInventario();
        inv.setVisible(true);
        DeskTop.add(inv);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenuPedidosFeitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPedidosFeitosActionPerformed
        TelaPedidosFeitos feito = new TelaPedidosFeitos();
        feito.setVisible(true);
        DeskTop.add(feito);
        LblSibre.setVisible(false);
    }//GEN-LAST:event_MenuPedidosFeitosActionPerformed

    private void MenuPedido_OracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPedido_OracaoActionPerformed
        PedidosdeOraçoes oracoes = new PedidosdeOraçoes();
        oracoes.setVisible(true);
        //DeskTop.add(oracoes);
        //LblSibre.setVisible(false);
    }//GEN-LAST:event_MenuPedido_OracaoActionPerformed

    private void MenuRelMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelMemActionPerformed
//        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão desse deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
//        if (confirma == JOptionPane.YES_OPTION) {
//            conexao.conector();
//            //imprimindo o relatório com o framework JasperReports
//            try {
//                conexao.executaSQL("select * from cadastro;");
//                JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
//                JasperPrint print = JasperFillManager.fillReport("src/Relatórios/Cad.jasper", new HashMap(), relatResult);
//                JasperViewer jv = new JasperViewer(print, false); //Cria instancia para impressão
//                jv.setVisible(true); //chama o relatório para visualização
//                jv.toFront(); // set o formuloari a frente da aplicação
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
////C:\Users\t69779848134\Documents\NetBeansProjects\ProjetoSibre1.9\src\Relatórios\Cad.jasper
//        }
    }//GEN-LAST:event_MenuRelMemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenCad;
    private javax.swing.JButton BtnMenuCant;
    private javax.swing.JButton BtnMenuFamilia;
    private javax.swing.JDesktopPane DeskTop;
    private javax.swing.JLabel LblSibre;
    private javax.swing.JMenu MenAjuda;
    public static javax.swing.JMenuItem MenCad;
    private javax.swing.JMenuItem MenCantina;
    public static javax.swing.JMenuItem MenFami;
    public static javax.swing.JMenuItem MenInv;
    public static javax.swing.JMenu MenRel;
    private javax.swing.JMenuItem MenRelCantina;
    public static javax.swing.JMenuItem MenRelFamilia;
    private javax.swing.JMenu MenSobre;
    private javax.swing.JMenuItem MenSobreOpc;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem MenuOpSair;
    private javax.swing.JMenuItem MenuPedido_Oracao;
    private javax.swing.JMenuItem MenuPedidosFeitos;
    public static javax.swing.JMenuItem MenuRelInventario;
    public static javax.swing.JMenuItem MenuRelMem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
