/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Sibre.Telas;

import java.sql.*;
import br.com.Sibre.Inventarios.InventarioBLL;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import br.com.Sibre.DAL.ModuloConexao;

/**
 *
 * @author t69779848134
 */
public class TelaInventario extends javax.swing.JInternalFrame {

    PreparedStatement pst;
    ResultSet rs;

    public void pesquisaInv() {
        ModuloConexao conexao = new ModuloConexao();
        conexao.conector();
        String sql = "select id_iv as Codigo, descricao as Descrição, quant as Quantidade, valorE as Valor, dataq as Dati from inventario where descricao like ?";

        try {
            pst = conexao.conn.prepareStatement(sql);
            pst.setString(1, InvPesq.getText() + "%");
            rs = pst.executeQuery();
            // a linha abaixo usa a biblioteca rs2xml.jar
            InvTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarInv() {
        int setar = InvTable.getSelectedRow();
        InvId.setText(InvTable.getModel().getValueAt(setar, 0).toString());
        InvDesc.setText(InvTable.getModel().getValueAt(setar, 1).toString());
        InvQuant.setText(InvTable.getModel().getValueAt(setar, 2).toString());
        InvValor.setText(InvTable.getModel().getValueAt(setar, 3).toString());

        // a linha a baixo desabilita o butao adicionar
        BtnInvAdic.setEnabled(false);
    }

    public void LimpaTela(){
        InvId.setText(null);
        InvDesc.setText(null);
        InvQuant.setText(null);
        InvValor.setText(null);
    }
    
    /**
     * Creates new form TelaProduto
     */
    public TelaInventario() {
        initComponents();
    }
    InventarioBLL bll = new InventarioBLL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnInvAdic = new javax.swing.JButton();
        BtnInvAlterar = new javax.swing.JButton();
        BtnInvDel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        InvQuant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InvValor = new javax.swing.JTextField();
        InvDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InvId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InvTable = new javax.swing.JTable();
        InvPesq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(209, 218, 218));
        setClosable(true);
        setIconifiable(true);
        setTitle("Tela de Inventario");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1130, 614));
        setPreferredSize(new java.awt.Dimension(1130, 614));

        jPanel1.setBackground(new java.awt.Color(154, 207, 217));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtnInvAdic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnInvAdic.setText("Adicionar");
        BtnInvAdic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInvAdic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvAdicActionPerformed(evt);
            }
        });

        BtnInvAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnInvAlterar.setText("ALterar");
        BtnInvAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInvAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvAlterarActionPerformed(evt);
            }
        });

        BtnInvDel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnInvDel.setText("Apagar");
        BtnInvDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInvDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInvDelActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Novo");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        InvQuant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantidade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Valor Estimado:");

        InvValor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        InvDesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descricao");

        InvId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InvId.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id");

        InvTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        InvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(InvTable);

        InvPesq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InvPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InvPesqKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pesquisa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InvPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(InvQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(27, 27, 27)
                            .addComponent(InvValor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(InvDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnInvAdic, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(BtnInvAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(BtnInvDel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InvQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(InvValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInvAdic, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInvAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInvDel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1130, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInvAdicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvAdicActionPerformed
        String descrica = this.InvDesc.getText();
        String quant = this.InvQuant.getText();
        String valor = this.InvValor.getText();
        bll.adicionar(descrica, quant, valor);
         LimpaTela();
    }//GEN-LAST:event_BtnInvAdicActionPerformed

    private void InvPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InvPesqKeyReleased
        pesquisaInv();
    }//GEN-LAST:event_InvPesqKeyReleased

    private void InvTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvTableMouseClicked
        setarInv();
    }//GEN-LAST:event_InvTableMouseClicked

    private void BtnInvAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvAlterarActionPerformed
        int id = Integer.parseInt(InvId.getText().toString());
        String descrica = this.InvDesc.getText();
        String quant = this.InvQuant.getText();
        String valor = this.InvValor.getText();
        
        bll.Alterar(id, descrica, quant, valor);
         LimpaTela();
    }//GEN-LAST:event_BtnInvAlterarActionPerformed

    private void BtnInvDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInvDelActionPerformed
        int id = Integer.parseInt(InvId.getText().toString());
        String descrica = this.InvDesc.getText();
        String quant = this.InvQuant.getText();
        String valor = this.InvValor.getText();
        
      bll.Excluir(id, descrica, quant, valor);
       LimpaTela();
    }//GEN-LAST:event_BtnInvDelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LimpaTela();
        BtnInvAdic.setEnabled(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInvAdic;
    private javax.swing.JButton BtnInvAlterar;
    private javax.swing.JButton BtnInvDel;
    private javax.swing.JTextField InvDesc;
    private javax.swing.JTextField InvId;
    private javax.swing.JTextField InvPesq;
    private javax.swing.JTextField InvQuant;
    private javax.swing.JTable InvTable;
    private javax.swing.JTextField InvValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
